experiment:
  name: stage2_clip5_official_transformer_conv_dcsa_pose2emg_stage1_h512_l3_code126
  seed: 730

runtime:
  device: cuda
  num_workers: 8
  log_every: 25
  max_steps: 20000
  save_every: 1000
  eval_every: 400
  grad_clip_norm: 1.0
  distributed:
    enabled: false
    gpus: [0]
    backend: nccl

optimizer:
  lr: 0.0001
  weight_decay: 0.0001
  warmup_steps: 600
  lr_schedule: cosine_annealing
  lr_min: 8.0e-6

data:
  split: train
  batch_size: 16
  step: 30
  joints3d_root_center: true
  joints3d_root_index: 8
  cond: "False"
  std: "False"
  percent: 1.0
  emg_normalize_target: true
  train_filelist: custom/tools/datasetsplits/miaofficial_train.txt
  val_filelist: custom/tools/datasetsplits/miaofficial_val_eval.txt
  max_samples: null
  require_files:
    - emgvalues.npy
    - joints3d.npy

stage1:
  checkpoint: custom/checkpoints/new_clip5_codebook_with_exerciseloss/exp_shared_head_h512_l3_code126/best.pt

checkpoints:
  dir: custom/stage2/checkpoints/lightweight_stage1_stage2/conv2d_in_dcsa/stage2_clip5_official_transformer_conv_dcsa_pose2emg_stage1_h512_l3_code126

model:
  task: "pose2emg"
  use_cond: false
  token_count: 1
  dim: 126
  cont_encoder_type: joint_25
  cont_hidden_dim: 1024
  cont_joint_hidden_dim: 128

  fusion_type: symmetric_dcsa
  dcsa:
    dim: 126
    num_heads: 7
    dropout: 0.2

  temporal_type: mia_official_transformer_conv_dcsa

  emg_head_type: identity
  emg_pred_mode: full
  max_seq_len: 256
